export type TileMedia = "image" | "video";

const workProjects = [
  {
    id: 1,
    src: "/projects/aasaan/tile.mp4",
    hoverSrc: "/projects/aasaan/hover.mp4",
    defaultMedia: "video",
    hoverMedia: "video",
    col: "col-span-1",
    row: "row-span-2",
    className: "!w-full !h-full",
    title: "AASAAN",
    description: [
      "Brand Strategy",
      "Product Feature Design",
      "Product Enhancement",
    ],
    subtitle:
      "Construction Management Platform | Digital Transformation Consulting",
    hoverClass: "absolute bottom-0 left-0 min-h-[12vw] rounded-b-current",
    hoverClassExtra: "",
    hoverListClass: "",
  },
  {
    id: 2,
    src: "/projects/waste-to-energy/tile.png",
    hoverSrc: "/projects/waste-to-energy/hover.mp4",
    defaultMedia: "image",
    hoverMedia: "video",
    col: "col-span-1",
    row: "row-span-1",
    className: "!w-full !h-full",
    title: "WASTE TO ENERGY",
    description: [
      "Management Consulting",
      "Design & master planning",
      "Project Execution",
    ],
    subtitle: "Clean India Mission | Energy Transition",
    hoverClass: "absolute bottom-0 left-0 h-[12vw] rounded-b-current w-full",
    hoverClassExtra: "",
    hoverListClass: "",
  },
  {
    id: 3,
    src: "/projects/stackbuilder/tile.png",
    hoverSrc: "/projects/stackbuilder/hover.mp4",
    defaultMedia: "image",
    hoverMedia: "video",
    col: "col-span-1",
    row: "row-span-1",
    className: "!w-full !h-full",
    title: "STACKBUILDER",
    description: ["Website Design", "Branding", "UX Lead"],
    subtitle: "Content & Marketing | Creative Consulting",
    hoverClass: "absolute bottom-0 left-0 h-[12vw] w-full rounded-b-current",
    hoverClassExtra: "",
    hoverListClass: "",
  },
  {
    id: 4,
    src: "/projects/eusotrip/tile.jpg",
    hoverSrc: "/projects/eusotrip/hover.mp4",
    defaultMedia: "image",
    hoverMedia: "video",
    col: "col-span-1",
    row: "row-span-1",
    className: "!w-full !h-full",
    title: "EUSOTRIP",
    description: [
      "Visual Identity",
      "Investor Pitch",
      "UI Flow",
      "Prototype Design",
    ],
    subtitle:
      "HazMat Logistics | Digital Platform | B2B industrial logistics solution",
    hoverClass: "absolute top-0 left-0 min-h-[11vw] w-full rounded-t-current",
    hoverClassExtra: "",
    hoverListClass: "",
  },
  {
    id: 5,
    src: "/projects/gcapita/tile.png",
    hoverSrc: "/projects/gcapita/hover.mp4",
    defaultMedia: "image",
    hoverMedia: "video",
    col: "col-span-1",
    row: "row-span-2",
    className: "!w-full !h-full",
    title: "G-CAPITA",
    description: [
      "Product Identity",
      "Business Analysis",
      "Product Prototype",
      "Dashboard Design",
    ],
    subtitle: "Investment Platform | Crypto-Commodities-Stocks",
    hoverClass:
      "absolute bottom-0 left-0 min-h-[11vw] w-full rounded-b-current",
    hoverClassExtra: "",
    hoverListClass: "",
  },
  {
    id: 6,
    src: "/projects/spendo/tile.png",
    hoverSrc: "/projects/spendo/hover.mp4",
    defaultMedia: "image",
    hoverMedia: "video",
    col: "col-span-2",
    row: "row-span-1",
    className: "!w-full !h-full",
    title: "SPENDO",
    description: ["Website Design", "Product UX"],
    subtitle: "Corporate petty cash management solution",
    hoverClass: "absolute bottom-0 right-0 w-[13rem] h-full rounded-r-current",
    hoverClassExtra: "flex-col flex-wrap items-start space-y-5",
    hoverListClass: "text-left w-full",
  },
  {
    id: 7,
    src: "/projects/pawsome/tile.mp4",
    hoverSrc: "/projects/pawsome/hover.jpg",
    defaultMedia: "video",
    hoverMedia: "image",
    col: "col-span-1",
    row: "row-span-1",
    className: "!w-full !h-full rounded-current",
    title: "PAWSOME",
    description: ["Product Research", "User Experience", "Design Mockups"],
    subtitle: "Pet Platform for Connecting | Pet enthusiasts as a community",
    hoverClass:
      "absolute bottom-0 left-0 min-h-[10vw] w-full rounded-b-current",
    hoverClassExtra: "",
  },
  {
    id: 8,
    src: "/projects/construct360/tile.png",
    hoverSrc: "/projects/construct360/hover.mp4",
    defaultMedia: "image",
    hoverMedia: "video",
    col: "col-span-2",
    row: "row-span-1",
    className: "!w-full !h-full rounded-current",
    title: "CONSTRUCT360",
    description: [
      "Dashboard Design",
      "User Experience",
      "Project Collaboration",
    ],
    subtitle:
      "Business Intelligence | Internal Construction Project Management System",
    hoverClass: "absolute bottom-0 right-0 w-[15rem] h-full rounded-r-current",
    hoverClassExtra: "flex-col flex-wrap items-start space-y-5",
    hoverListClass: "text-left w-full",
  },
  {
    id: 9,
    src: "/projects/unesco-chair/tile.png",
    hoverSrc: "/projects/unesco-chair/hover.mp4",
    defaultMedia: "image",
    hoverMedia: "video",
    col: "col-span-1",
    row: "row-span-2",
    className: "!w-full !h-full rounded-current",
    title: "UNESCO CHAIR",
    description: ["Proposal", "Curating", "Content Strategy", "Digital Media"],
    subtitle: "International Academic Association | University of Hyderabad",
    hoverClass:
      "absolute left-0 inset-1/2 -translate-y-[60%] min-h-[16vw] w-full",
    hoverClassExtra: "",
    hoverListClass: "",
  },
  {
    id: 10,
    src: "/projects/kafzeit/tile.mp4",
    hoverSrc: "/projects/kafzeit/hover.mp4",
    defaultMedia: "video",
    hoverMedia: "video",
    col: "col-span-1",
    row: "row-span-1",
    className: "!w-full !h-full rounded-current",
    title: "Kafzeit",
    description: [
      "Market Research",
      "Experience  Design",
      "Brand Consulting",
      "Digital Store",
    ],
    subtitle: "Coffee House in Berlin | Business Consulting",
    hoverClass: "absolute bottom-0 right-0 w-[12rem] h-full rounded-r-current",
    hoverClassExtra: "flex-col flex-wrap items-start space-y-5",
    hoverListClass: "text-left w-full",
  },
  {
    id: 11,
    src: "/projects/digital-transformation/tile.png",
    hoverSrc: "/projects/digital-transformation/hover.mp4",
    defaultMedia: "image",
    hoverMedia: "video",
    col: "col-span-1",
    row: "row-span-1",
    className: "!w-full !h-full rounded-current",
    title: "DIGITAL TRANSFORMATION",
    description: ["Proposal ", "Methodology", "Business Development Strategy"],
    subtitle: "Master Thesis | Management Research",
    hoverClass:
      "absolute bottom-0 left-0 min-h-[12vw] w-full rounded-b-current",
  },
  {
    id: 12,
    src: "/projects/mitmut-studio/tile.mp4",
    hoverSrc: "/projects/mitmut-studio/hover.png",
    defaultMedia: "video",
    hoverMedia: "image",
    col: "col-span-2",
    row: "row-span-1",
    className: "!w-full !h-full rounded-current",
    title: "MITMUT STUDIO",
    description: ["Business Model", "Investor Pitch", "Product Visuals"],
    subtitle:
      "Pressed Funding for Product Development | Eduverse as Gamified Learning Experience  ",
    hoverClass: "absolute bottom-0 right-0 w-[230px] h-full rounded-r-current",
    hoverClassExtra: "flex-col flex-wrap items-start space-y-5",
    hoverListClass: "text-left w-full",
  },
];

export default workProjects;
