export type TileMedia = "image" | "video";

const workProjects = [
  {
    id: 1,
    src: "/projects/aasaan/tile.mp4",
    hoverSrc: "/projects/aasaan/hover.mp4",
    defaultMedia: "video",
    hoverMedia: "video",
    col: "col-span-1",
    row: "row-span-2",
    className: "!w-full !h-full",
    title: "AASAAN",
    subtitle:
      "POCKET CONSTRUCTION MANAGER | PRODUCT STRATEY",
    hoverClass: "absolute bottom-0 left-0 min-h-[11.5vw] w-full rounded-b-current",
    hoverBgClass: "bg-dark-charcoal",
    hoverTitleClass: "text-theme-overlay-text",
    hoverSubtitleClass: "text-theme-overlay-text opacity-80 !font-source-code uppercase",
  },
  {
    id: 2,
    src: "/projects/waste-to-energy/tile.png",
    hoverSrc: "/projects/waste-to-energy/hover.mp4",
    defaultMedia: "image",
    hoverMedia: "video",
    col: "col-span-1",
    row: "row-span-1",
    className: "!w-full !h-full",
    title: "WASTE TO ENERGY",
    subtitle: "Infrastructure | Management Consulting",
    hoverClass: "absolute bottom-0 left-0 h-[10vw] rounded-b-current w-full",
    hoverBgClass: "bg-dark-charcoal",
    hoverTitleClass: "text-theme-overlay-text",
    hoverSubtitleClass: "text-theme-overlay-text opacity-80 !font-source-code uppercase",
    hoverClassExtra: "",
    hoverListClass: "",
    link: "/work/wastetoenergy",
  },
  {
    id: 3,
    src: "/projects/stackbuilder/tile.png",
    hoverSrc: "/projects/stackbuilder/hover.mp4",
    defaultMedia: "image",
    hoverMedia: "video",
    col: "col-span-1",
    row: "row-span-1",
    className: "!w-full !h-full",
    title: "STACK BUILDER",
    subtitle: "Web Design | Creative Consulting",
    hoverClass: "absolute bottom-0 left-0 h-[09vw] w-full rounded-b-current",
    hoverBgClass: "bg-dark-charcoal",
    hoverTitleClass: "text-theme-overlay-text",
    hoverSubtitleClass: "text-theme-overlay-text opacity-80 !font-source-code uppercase",
    hoverClassExtra: "",
    hoverListClass: "",
    link: "/work/stackbuilder",
  },
  {
    id: 4,
    src: "/projects/eusotrip/tile.jpg",
    hoverSrc: "/projects/eusotrip/hover.mp4",
    defaultMedia: "image",
    hoverMedia: "video",
    col: "col-span-1",
    row: "row-span-1",
    className: "!w-full !h-full",
    title: "EUSOTRIP",
    subtitle:
      "Logistics Platform | Product design",
    hoverClass: "absolute top-0 left-0 min-h-[8vw] w-full rounded-t-current",
    hoverBgClass: "bg-dark-charcoal",
    hoverTitleClass: "text-theme-overlay-text",
    hoverSubtitleClass: "text-theme-overlay-text opacity-80 !font-source-code uppercase",
    hoverClassExtra: "",
    hoverListClass: "",
    link: "/work/eusotrip",
  },
  {
    id: 5,
    src: "/projects/gcapital/tile.png",
    hoverSrc: "/projects/gcapital/hover.mp4",
    defaultMedia: "image",
    hoverMedia: "video",
    col: "col-span-1",
    row: "row-span-2",
    className: "!w-full !h-full",
    title: "G-CAPITAL",
    subtitle: "Investment Platform | product owner",
    hoverClass:
      "absolute bottom-0 left-0 min-h-[11vw] w-full rounded-b-current",
    hoverBgClass: "bg-dark-charcoal",
    hoverTitleClass: "text-theme-overlay-text",
    hoverSubtitleClass: "text-theme-overlay-text opacity-80 !font-source-code uppercase",
    hoverClassExtra: "",
    hoverListClass: "",
    link: "/work/gcapital",
  },
  {
    id: 6,
    src: "/projects/spendo/tile.png",
    hoverSrc: "/projects/spendo/hover.mp4",
    defaultMedia: "image",
    hoverMedia: "video",
    col: "col-span-2",
    row: "row-span-1",
    className: "!w-full !h-full",
    title: "SPENDO",
    subtitle: "Expense Management | Web App",
    hoverClass: "absolute bottom-0 right-0 w-[13rem] h-full rounded-r-current",
    hoverBgClass: "bg-dark-charcoal",
    hoverTitleClass: "text-theme-overlay-text",
    hoverSubtitleClass: "text-theme-overlay-text opacity-80 !font-source-code uppercase",
    hoverClassExtra: "flex-col flex-wrap items-start space-y-5",
    hoverListClass: "text-left w-full",
    link: "/work/spendo",
  },
  {
    id: 7,
    src: "/projects/pawsome/tile.mp4",
    hoverSrc: "/projects/pawsome/hover.jpg",
    defaultMedia: "video",
    hoverMedia: "image",
    col: "col-span-1",
    row: "row-span-1",
    className: "!w-full !h-full rounded-current",
    title: "PAWSOME",
    subtitle: "Pet Platform  | Product visualisation",
    hoverClass:
      "absolute bottom-0 left-0 min-h-[05vw] w-full rounded-b-current",
    hoverBgClass: "bg-dark-charcoal",
    hoverTitleClass: "text-theme-overlay-text",
    hoverSubtitleClass: "text-theme-overlay-text opacity-80 !font-source-code uppercase",
    hoverClassExtra: "",
    hoverListClass: "",
    link: "/work/pawsome"
  },
  {
    id: 8,
    src: "/projects/construct360/tile.png",
    hoverSrc: "/projects/construct360/hover.mp4",
    defaultMedia: "image",
    hoverMedia: "video",
    col: "col-span-2",
    row: "row-span-1",
    className: "!w-full !h-full rounded-current",
    title: "CONSTRUCT360",
    subtitle:
      "Business Intelligence | Project Collaboration",
    hoverClass: "absolute bottom-0 right-0 w-[15rem] h-full rounded-r-current",
    hoverBgClass: "bg-dark-charcoal",
    hoverTitleClass: "text-theme-overlay-text",
    hoverSubtitleClass: "text-theme-overlay-text opacity-80 !font-source-code uppercase",
    hoverClassExtra: "flex-col flex-wrap items-start space-y-5",
    hoverListClass: "text-left w-full",
    link: "/work/construct360",
  },
  {
    id: 9,
    src: "/projects/unesco-chair/tile.png",
    hoverSrc: "/projects/unesco-chair/hover.mp4",
    defaultMedia: "image",
    hoverMedia: "video",
    col: "col-span-1",
    row: "row-span-2",
    className: "!w-full !h-full rounded-current",
    title: "UNESCO CHAIR",
    subtitle: "Project Collaboration | Curation",
    hoverClass:
      "absolute left-0 inset-1/2 -translate-y-[60%] min-h-[15vw] w-full",
    hoverBgClass: "bg-dark-charcoal",
    hoverTitleClass: "text-theme-overlay-text",
    hoverSubtitleClass: "text-theme-overlay-text opacity-80 !font-source-code uppercase",
    hoverClassExtra: "",
    hoverListClass: "",
    link: "/work/unesco-chair",
  },
  {
    id: 10,
    src: "/projects/kafzeit/tile.mp4",
    hoverSrc: "/projects/kafzeit/hover.mp4",
    defaultMedia: "video",
    hoverMedia: "video",
    col: "col-span-1",
    row: "row-span-1",
    className: "!w-full !h-full rounded-current",
    title: "KAFZEIT",
    subtitle: "Digital Store | brand Consulting",
    hoverClass: "absolute bottom-0 right-0 w-[12.5rem] h-full rounded-r-current",
    hoverBgClass: "bg-dark-charcoal",
    hoverTitleClass: "text-theme-overlay-text",
    hoverSubtitleClass: "text-theme-overlay-text opacity-80 !font-source-code uppercase",
    hoverClassExtra: "flex-col flex-wrap items-start space-y-5",
    hoverListClass: "text-left w-full",
    link: "/work/kafzeit",
  },
  {
    id: 11,
    src: "/projects/digital-transformation/tile.png",
    hoverSrc: "/projects/digital-transformation/hover.mp4",
    defaultMedia: "image",
    hoverMedia: "video",
    col: "col-span-1",
    row: "row-span-1",
    className: "!w-full !h-full rounded-current",
    title: "DIGITAL TRANSFORMATION",
    subtitle: "Master's Thesis | Management Research",
    hoverClass:
      "absolute bottom-0 left-0 min-h-[10vw] w-full rounded-b-current",
    hoverBgClass: "bg-dark-charcoal",
    hoverTitleClass: "text-theme-overlay-text",
    hoverSubtitleClass: "text-theme-overlay-text opacity-80 !font-source-code uppercase",
    hoverClassExtra: "",
    hoverListClass: "",
    link: "/work/digital-transformation",
  },
  {
    id: 12,
    src: "/projects/mitmut-studio/tile.mp4",
    hoverSrc: "/projects/mitmut-studio/hover.png",
    defaultMedia: "video",
    hoverMedia: "image",
    col: "col-span-2",
    row: "row-span-1",
    className: "!w-full !h-full rounded-current",
    title: "MITMUT STUDIO",
    subtitle:
      "Edutech Platform | Product Research",
    hoverClass: "absolute bottom-0 right-0 w-[230px] h-full rounded-r-current",
    hoverBgClass: "bg-dark-charcoal",
    hoverTitleClass: "text-theme-overlay-text",
    hoverSubtitleClass: "text-theme-overlay-text opacity-80 !font-source-code uppercase",
    hoverClassExtra: "flex-col flex-wrap items-start space-y-5",
    hoverListClass: "text-left w-full",
    link: "/work/mitmut-studio",
  },
];

export default workProjects;
